import React from "react";
import { RetrievedEvidence } from "../../types/api";

interface RagEvidenceDrawerProps {
  isOpen: boolean;
  onClose: () => void;
  evidenceList: RetrievedEvidence[];
}

export const RagEvidenceDrawer: React.FC<RagEvidenceDrawerProps> = ({
  isOpen,
  onClose,
  evidenceList
}) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex justify-end bg-background/70 backdrop-blur-sm transition-opacity">
      <div className="w-full max-w-2xl bg-surface-container-lowest border-l border-surface-border h-full flex flex-col shadow-2xl overflow-hidden animate-in slide-in-from-right duration-300">
        {/* Drawer Header */}
        <div className="h-16 border-b border-surface-border px-6 flex items-center justify-between bg-surface-container-low/60">
          <div className="flex items-center gap-2">
            <span className="material-symbols-outlined text-secondary text-xl">
              library_books
            </span>
            <div>
              <h2 className="font-mono text-sm font-bold text-slate-100 uppercase tracking-wider">
                RAG Scientific Evidence Inspector
              </h2>
              <p className="text-[10px] font-mono text-slate-400">
                Ground-truth peer-reviewed documents indexed in ChromaDB
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-1.5 rounded-md hover:bg-surface-container text-slate-400 hover:text-slate-200 transition-colors"
          >
            <span className="material-symbols-outlined text-lg">close</span>
          </button>
        </div>

        {/* Evidence List */}
        <div className="flex-1 overflow-y-auto p-6 space-y-4">
          <div className="bg-surface-container/60 p-3 rounded-lg border border-surface-border text-xs text-slate-300 font-sans leading-relaxed">
            <strong className="text-secondary font-mono text-[11px] block mb-1">
              ZERO HALLUCINATION AUDIT POLICY
            </strong>
            Every piece of evidence displayed below is retrieved directly from our indexed ChromaDB vector store.
            No citations, DOIs, authors, or statistics are generated by LLM imagination.
          </div>

          {evidenceList.length === 0 ? (
            <div className="text-center py-12 text-slate-500 font-mono text-xs">
              Knowledge retrieval unavailable or no query active yet.
            </div>
          ) : (
            evidenceList.map((ev, idx) => (
              <div
                key={ev.document_id || idx}
                className="bg-surface-container-low border border-surface-border rounded-lg p-4 space-y-3 shadow-md"
              >
                {/* Top: Doc ID & Similarity Score */}
                <div className="flex items-center justify-between">
                  <span className="font-mono text-[10px] px-2 py-0.5 rounded bg-surface-container text-secondary border border-surface-border font-bold">
                    {ev.document_id}
                  </span>
                  <div className="flex items-center gap-2">
                    <span className="text-[10px] font-mono text-slate-400">
                      RELEVANCE:
                    </span>
                    <span className="font-mono text-[11px] font-bold text-primary px-2 py-0.5 rounded bg-primary/10 border border-primary/30">
                      {(ev.similarity_score * 100).toFixed(1)}%
                    </span>
                  </div>
                </div>

                {/* Title & Author */}
                <div className="space-y-0.5">
                  <h3 className="font-sans font-bold text-sm text-slate-100 leading-snug">
                    {ev.title}
                  </h3>
                  <div className="text-xs text-slate-400 font-mono">
                    {ev.organization} ({ev.publication_year}) • {ev.environmental_domain}
                  </div>
                </div>

                {/* Excerpt */}
                <div className="p-3 rounded bg-surface-container-lowest/80 border border-surface-border/70 text-xs text-slate-300 font-sans leading-relaxed">
                  "{ev.excerpt}"
                </div>

                {/* Matched Variables */}
                {ev.variables && ev.variables.length > 0 && (
                  <div className="flex flex-wrap items-center gap-1.5 pt-1">
                    <span className="text-[10px] font-mono text-slate-500">
                      MATCHED METRICS:
                    </span>
                    {ev.variables.map((v) => (
                      <span
                        key={v}
                        className="px-1.5 py-0.5 rounded bg-surface-container text-[10px] font-mono text-emerald-300"
                      >
                        {v.replace(/_/g, " ")}
                      </span>
                    ))}
                  </div>
                )}

                {/* Citation & URL */}
                <div className="pt-2 border-t border-surface-border/50 flex items-center justify-between text-[11px]">
                  <span className="text-slate-500 font-mono text-[10px] truncate max-w-[320px]">
                    {ev.citation}
                  </span>
                  {ev.url && (
                    <a
                      href={ev.url}
                      target="_blank"
                      rel="noreferrer"
                      className="inline-flex items-center gap-1 text-primary hover:underline font-mono text-[10px] font-bold"
                    >
                      <span>OFFICIAL SOURCE</span>
                      <span className="material-symbols-outlined text-xs">open_in_new</span>
                    </a>
                  )}
                </div>
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  );
};
