import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from app.services.db_service import db_service

SEED_OBSERVATIONS = [
    {
        "id": "CASE-01-SEMIARID-WHEAT",
        "location_name": "Arid Plains Farm (Hackathon Demo)",
        "latitude": 31.9505,
        "longitude": 35.9333,
        "region": "semi-arid",
        "country": "Jordan/Levant",
        "climate_zone": "BSh (Hot semi-arid)",
        "soil_ph": 6.8,
        "soil_organic_carbon": 0.3,
        "soil_moisture": 18.0,
        "land_use": "monoculture wheat",
        "land_cover": "cropland",
        "monoculture_or_polyculture": "monoculture",
        "habitat_diversity": "low",
        "habitat_fragmentation": "moderate",
        "species_richness": "low",
        "species_diversity": "low",
        "pollinator_presence": "low",
        "microbial_diversity": "low",
        "temperature": 31.0,
        "rainfall": "low",
        "rainfall_variability": "high",
        "drought_condition": "active",
        "pollution_level": "moderate",
        "pesticide_intensity": "moderate",
        "deforestation_level": "low",
        "urbanization": "low",
        "land_disturbance": "high tillage",
        "water_availability": "scarce",
        "irrigation": "none (rainfed)",
        "water_stress": "high"
    },
    {
        "id": "CASE-02-HIGHRAIN-PESTICIDE",
        "location_name": "Valley Intensive Orchard",
        "latitude": 44.4949,
        "longitude": 11.3426,
        "region": "sub-humid river valley",
        "country": "Italy",
        "climate_zone": "Cfa (Humid subtropical)",
        "soil_ph": 6.4,
        "soil_organic_carbon": 1.4,
        "soil_moisture": 45.0,
        "land_use": "intensive fruit orchard",
        "land_cover": "orchard",
        "monoculture_or_polyculture": "monoculture",
        "habitat_diversity": "low",
        "habitat_fragmentation": "moderate",
        "species_richness": "low",
        "species_diversity": "low",
        "pollinator_presence": "low",
        "microbial_diversity": "moderate",
        "temperature": 22.0,
        "rainfall": "high",
        "rainfall_variability": "moderate",
        "drought_condition": "none",
        "pollution_level": "moderate",
        "pesticide_intensity": "high",
        "deforestation_level": "low",
        "urbanization": "low",
        "land_disturbance": "moderate",
        "water_availability": "abundant",
        "irrigation": "drip available",
        "water_stress": "none"
    },
    {
        "id": "CASE-03-URBAN-FRINGE",
        "location_name": "Metro Perimeter Remnant Green",
        "latitude": 51.5074,
        "longitude": -0.1278,
        "region": "urban-fringe peri-urban zone",
        "country": "United Kingdom",
        "climate_zone": "Cfb (Oceanic)",
        "soil_ph": 7.4,
        "soil_organic_carbon": 1.1,
        "soil_moisture": 32.0,
        "land_use": "fragmented pasture and horticulture",
        "land_cover": "fragmented scrub & grass",
        "monoculture_or_polyculture": "polyculture",
        "habitat_diversity": "low",
        "habitat_fragmentation": "high",
        "species_richness": "low",
        "species_diversity": "low",
        "pollinator_presence": "moderate",
        "microbial_diversity": "low",
        "temperature": 18.0,
        "rainfall": "moderate",
        "rainfall_variability": "low",
        "drought_condition": "none",
        "pollution_level": "high",
        "pesticide_intensity": "low",
        "deforestation_level": "historical",
        "urbanization": "high",
        "land_disturbance": "high",
        "water_availability": "moderate",
        "irrigation": "none",
        "water_stress": "low"
    },
    {
        "id": "CASE-04-DEGRADED-AGRI",
        "location_name": "Over-tilled Prairie Basin",
        "latitude": 38.9072,
        "longitude": -95.6814,
        "region": "degraded agricultural prairie",
        "country": "United States",
        "climate_zone": "Dfa (Hot summer continental)",
        "soil_ph": 5.2,
        "soil_organic_carbon": 0.5,
        "soil_moisture": 12.0,
        "land_use": "continuous conventional corn",
        "land_cover": "arable bare topsoil",
        "monoculture_or_polyculture": "monoculture",
        "habitat_diversity": "very low",
        "habitat_fragmentation": "high",
        "species_richness": "very low",
        "species_diversity": "low",
        "pollinator_presence": "low",
        "microbial_diversity": "severely depleted",
        "temperature": 34.0,
        "rainfall": "low",
        "rainfall_variability": "high",
        "drought_condition": "severe",
        "pollution_level": "moderate",
        "pesticide_intensity": "high",
        "deforestation_level": "complete",
        "urbanization": "low",
        "land_disturbance": "extreme moldboard tillage",
        "water_availability": "depleted",
        "irrigation": "center pivot",
        "water_stress": "extreme"
    },
    {
        "id": "CASE-05-HEALTHY-SOIL",
        "location_name": "Regenerative Agroforestry Homestead",
        "latitude": 46.8182,
        "longitude": 8.2275,
        "region": "temperate alpine foothills",
        "country": "Switzerland",
        "climate_zone": "Cfb (Montane temperate)",
        "soil_ph": 6.8,
        "soil_organic_carbon": 3.8,
        "soil_moisture": 38.0,
        "land_use": "mixed rotational polyculture and silvopasture",
        "land_cover": "wooded pasture and multispecies canopy",
        "monoculture_or_polyculture": "polyculture",
        "habitat_diversity": "high",
        "habitat_fragmentation": "low",
        "species_richness": "high",
        "species_diversity": "high",
        "pollinator_presence": "high",
        "microbial_diversity": "high",
        "temperature": 21.0,
        "rainfall": "moderate",
        "rainfall_variability": "low",
        "drought_condition": "none",
        "pollution_level": "low",
        "pesticide_intensity": "none (organic)",
        "deforestation_level": "none",
        "urbanization": "low",
        "land_disturbance": "no-till continuous living roots",
        "water_availability": "abundant",
        "irrigation": "rainfed",
        "water_stress": "none"
    }
]

def seed_observations():
    print("Seeding SQLite database with 5 official environmental test cases...")
    for obs in SEED_OBSERVATIONS:
        saved_id = db_service.save_observation(obs)
        print(f" -> Stored [{saved_id}]: {obs['location_name']}")
    print("Database seeding completed.")

if __name__ == "__main__":
    seed_observations()
