/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error": "#ffb4ab",
        "inverse-surface": "#e1e2ea",
        "secondary-fixed-dim": "#4cd7f6",
        "primary": "#4edea3",
        "on-primary-fixed": "#002113",
        "surface-container-lowest": "#0b0e13",
        "secondary-fixed": "#acedff",
        "secondary": "#4cd7f6",
        "on-primary-container": "#00422b",
        "on-primary": "#003824",
        "on-secondary-fixed": "#001f26",
        "outline": "#86948a",
        "surface-container-highest": "#32353b",
        "tertiary-fixed": "#ffddb8",
        "on-secondary-container": "#00424e",
        "inverse-primary": "#006c49",
        "surface-variant": "#32353b",
        "inverse-on-surface": "#2e3036",
        "on-error-container": "#ffdad6",
        "on-tertiary": "#472a00",
        "error-container": "#93000a",
        "outline-variant": "#3c4a42",
        "tertiary": "#ffb95f",
        "on-surface": "#e1e2ea",
        "on-surface-variant": "#bbcabf",
        "surface-tint": "#4edea3",
        "background": "#111319",
        "on-tertiary-container": "#523200",
        "on-tertiary-fixed": "#2a1700",
        "primary-container": "#10b981",
        "surface-dim": "#111319",
        "surface-bright": "#36393f",
        "tertiary-container": "#e29100",
        "tertiary-fixed-dim": "#ffb95f",
        "on-background": "#e1e2ea",
        "on-secondary": "#003640",
        "on-primary-fixed-variant": "#005236",
        "surface": "#111319",
        "primary-fixed-dim": "#4edea3",
        "on-error": "#690005",
        "secondary-container": "#03b5d3",
        "primary-fixed": "#6ffbbe",
        "on-tertiary-fixed-variant": "#653e00",
        "surface-container-low": "#191c21",
        "on-secondary-fixed-variant": "#004e5c",
        "surface-container-high": "#272a30",
        "surface-container": "#1d2025"
      },
      fontFamily: {
        "body-sm": ["Geist", "sans-serif"],
        "telemetry-micro": ["JetBrains Mono", "monospace"],
        "telemetry-data": ["JetBrains Mono", "monospace"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "body-md": ["Geist", "sans-serif"],
        "display-command": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "telemetry-metric": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Space Grotesk", "sans-serif"]
      },
      fontSize: {
        "body-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" }],
        "telemetry-micro": ["10px", { lineHeight: "13px", letterSpacing: "0.05em", fontWeight: "400" }],
        "telemetry-data": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-caps": ["10px", { lineHeight: "12px", letterSpacing: "0.08em", fontWeight: "600" }],
        "body-md": ["13px", { lineHeight: "19px", letterSpacing: "0em", fontWeight: "400" }],
        "display-command": ["40px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "body-lg": ["15px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "headline-sm": ["16px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "500" }],
        "headline-md": ["20px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "telemetry-metric": ["24px", { lineHeight: "28px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }]
      }
    }
  },
  plugins: []
}
